version: "3"
services:
  urlshortner:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortner
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis
    ports:
      - "6379:6379"